repos:
-   repo: local
    hooks:
    -   id: check-yaml
        name: check yaml
        language: system
        entry: check-yaml
        types: [yaml]
    -   id: trailing-whitespace
        name: trailing whitespace
        language: system
        entry: trailing-whitespace-fixer
        types: [text]
    -   id: mixed-line-ending
        name: mixed line ending
        language: system
        entry: mixed-line-ending
        types: [text]
    -   id: end-of-file-fixer
        name: end of file fixer
        language: system
        entry: end-of-file-fixer
        types: [text]
    -   id: autopep8
        name: autopep8
        language: system
        entry: autopep8
        args: [--in-place]
        types: [python]
